volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

services:
  rating-system-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: rating-system-service:latest
    container_name: rating-system-service
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${PG_ADMIN}
      - SPRING_DATASOURCE_PASSWORD=${PG_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=your_secure_password
      - SERVER_PORT=9090
      - KEYCLOAK_REALM=leverx
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_RESOURCE=rating-system
      - MASTER_USER_USERNAME=admin
      - MASTER_USER_PASSWORD=admin
      - MASTER_REALM=master
      - MASTER_CLIENT=admin-cli
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics
    networks:
      - leverx-network
    depends_on:
      - redis
      - postgres
      - keycloak

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_ADMIN}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - leverx-network
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: rating-system-kc
    environment:
        KC_DB: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_URL_DATABASE: postgres
        KC_DB_USERNAME: ${PG_ADMIN}
        KC_DB_PASSWORD: ${PG_PASSWORD}
        KEYCLOAK_ADMIN: ${KC_ADMIN}
        KEYCLOAK_ADMIN_PASSWORD: ${KC_PASSWORD}
        KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    command: start-dev
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - leverx-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=your_secure_password  # Add a password for Redis
    command: [ "redis-server", "--requirepass", "your_secure_password" ]
    networks:
      - leverx-network

networks:
  leverx-network:
    driver: bridge